### ISSUE TITLE
Config file sanity checks

### ISSUE THREAD

**Issue by xolotl90** [XENON1T/pax#222]
Wouldn't it be good to have a sanity check for config files? 

For example, we had those issues with the TableWriter and the ignore =["hits", "all_hits"].  

I could also imagine other checks like that the initial_baseline_samples must not include the trigger signal.

**Comment by JelleAalbers** [comment]
By now several plugins do this for their own configuration, and some basic config checks on the pax core config are done in the pax core (e.g. presence of input plugin, waveform simulator section). I think this will accommodate checks we'll want in the future as well, otherwise we can reopen.
