### ISSUE TITLE
Consistent configuration file variables

### ISSUE THREAD

**Issue by pelssers** [XENON1T/pax#300]
There are currently some differences between XENON100 and XENON1T configuration variables. For example Xe100 uses `'pmt_locations'` to store PMT positions whereas Xe1T uses `'pmts'` which holds more information about the PMTs including their position. During #296 a workaround was put in plugin.py to deal with both options. In the future both configurations should use the `'pmts'` variable.

Maybe related to #222

**Comment by JelleAalbers** [comment]
Fixed in #339.
