### ISSUE TITLE
Add quantum efficiencies to XENON1T.ini

### ISSUE THREAD

**Issue by pelssers** [XENON1T/pax#346]
Currently all PMTs in XENON1T.ini have a QE of 0.35. Also the neural network used by default is the one without the QE implementation (it only makes sense to use the new one if the PMTs have different QE). 

Once we replace the placeholder QE values with the actual ones we should not forget to change the neural nets (simply change the filname in XENON1T.ini).

**Comment by JelleAalbers** [comment]
Good idea, does anyone know where these values are? Somewhere in the PMT group's database?

**Comment by weiyuehuan** [comment]
Hi Jelle, Yes, I used the QE values in PMT database for training the 
network last time:
https://xecluster.lngs.infn.it/xenon1tpmts/daniel_test/tpc_view_datasheets.php
Best, -Yuehuan

**Comment by JelleAalbers** [comment]
Ok, I added them now. Conversion code in case we need it again:

```
import pandas as pd
# Get csv from copy-pasting html table from browser into excel / amazing free crappy alternative
pmt_sheet = pd.read_csv('Projects/pmt_datasheet.csv')

from pax import configuration
pax_config = configuration.load_configuration('XENON1T')

pmt_sheet['serial'] = [int(x[2:]) for x in pmt_sheet['Serial Number '].values]

for pmt_data in pax_config['DEFAULT']['pmts']:
    pmt = pmt_data['pmt_position']
    serial_number = pmt_data['serial_number']
    if serial_number == -1:
        print("    0.350,    # %d, placeholder (serial number not known)" % pmt)
        qes.append(0.35)
        continue
    q = pmt_sheet[pmt_sheet.serial == serial_number]
    assert len(q) == 1
    q = q.iloc[0]
    print("    %0.3f,    # %d = KB%04d" % (q['QE at 175nm [%]'] * 0.01, pmt, serial_number))
```

Bart, do you need to change anything to the neural net? The test still works (on my machine at least).

**Comment by pelssers** [comment]
Hi Jelle,
Thanks for putting these numbers in. I'll swap the neural nets now.

**Comment by pelssers** [comment]
Done, pax now runs the QE weighted neural network.
