### ISSUE TITLE
Specify # of Cores in Processor Class

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#350]
Would it be possible to specify the number of CPU in the Processor class constructor, such that it may be used in multiprocessing mode in e.g. https://github.com/XENON1T/cax/blob/master/cax/tasks/process.py?

Thank you

**Comment by JelleAalbers** [comment]
Hi Patrick, sure, just add the `n_cpus` option to the configuration. For example, change
```
        p = core.Processor(config_names=pax_config,
                           config_dict={'pax': {'input_name' : location,
                                                'output_name': location}})
```

to 

```
        p = core.Processor(config_names=pax_config,
                           config_dict={'pax': {'input_name' : location,
                                                'output_name': location,
                                                'n_cpus': 42}})
```

It will spawn two more processed beyond the number you specify: one for input and one for output. These are usually light on the cpu.

**Comment by pdeperio** [comment]
worked, thanks! (except 42 too many)
