### ISSUE TITLE
WARNING Event has no pulses??! in recent files

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#352]
Discovered during pax processing:

```AttributeError: 'float' object has no attribute 'typecode'```

https://gist.github.com/pdeperio/041a4581a834986d19ee9e8b96902a42
Dataset: 160501_1733
Run: 346

https://gist.github.com/pdeperio/e6b28fdb21263f3428bdce0a18378cb3
Dataset: 160501_1745
Run: 347

Dataset: 160501_1750
Run: 348

Dataset: 160501_1756
Run: 349

**Comment by pdeperio** [comment]
Jelle discovered due to some changes in DAQ during commissioning...

**Comment by JelleAalbers** [comment]
A few datasets were taking with experimental clear-as-we-go that actually cleared the data a bit too soon: you end up with empty events (save for the trigger signals). Sorry! At least there is no mistaking when this occurs: datasets won't even process. Everything that did process is not affected.

**Comment by JelleAalbers** [comment]
This is a specific error due to a mistake in the trigger that is fixed now. It should not occur again, and the datasets for which it did occur are irrrecoverable. I'll close the issue.

**Comment by pdeperio** [comment]
Found more of these failures when re-processing with v4.10.0 (log files on Midway with base dir /project/lgrandi/xenon1t/processing):

```
234 160427_1851 160427_1851_v4.10.0/160427_1851_v4.10.0_18951001.log 
272 160428_2050 160428_2050_v4.10.0/160428_2050_v4.10.0_18941923.log 
346 160501_1733 160501_1733_v4.10.0/160501_1733_v4.10.0_18941947.log 
347 160501_1745 160501_1745_v4.10.0/160501_1745_v4.10.0_18941953.log 
348 160501_1750 160501_1750_v4.10.0/160501_1750_v4.10.0_18941948.log 
349 160501_1756 160501_1756_v4.10.0/160501_1756_v4.10.0_18941951.log 
350 160501_1817 160501_1817_v4.10.0/160501_1817_v4.10.0_18942166.log 
351 160501_1823 160501_1823_v4.10.0/160501_1823_v4.10.0_18942165.log 
352 160501_1826 160501_1826_v4.10.0/160501_1826_v4.10.0_18941949.log 
```

Can you confirm that these new files are indeed affected by the same "experimental clear-as-we-go" you mentioned?

Is there a way to avoid these datasets so the jobs don't get submitted during re-processing or cax re-trying? (Some of them eat up the entire walltime limit.)

**Comment by tunnell** [comment]
Delete the data.  It's DAQ test.

**Comment by tunnell** [comment]
Actually, computing chat.  Maybe your idea is better.



From: Christopher Tunnell <ctunnell@nikhef.nl>
Reply: Christopher Tunnell <ctunnell@nikhef.nl>
Date: 25 May 2016 at 18:41:21
To: XENON1T/pax <reply@reply.github.com>, XENON1T/pax <pax@noreply.github.com>, Patrick de Perio <notifications@github.com>
Subject:  Re: [XENON1T/pax] WARNING Event has no pulses??! in recent files (#352)  

Delete the data.  It's DAQ test.

**Comment by pdeperio** [comment]
ok added "donotprocess" tag to these files.
