### ISSUE TITLE
Error: zipfile.BadZipFile: File is not a zip file 

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#358]
pax v4.9.3 (head) crash while processing Run 552 (Dataset 160515_0920):

https://gist.github.com/pdeperio/161e5532f1a52b9696a348dd51d574e1

Logs and job scripts can be found on Midway: /project/lgrandi/xenon1t/processing/160515_0920

**Comment by JelleAalbers** [comment]
Looks like the raw data transfer to midway is not complete, it still says 'transferring'. The error you get is also consistent with raw data corruption. I wonder why cax decided to start processing it, even if the data has not yet arrived?

**Comment by JelleAalbers** [comment]
Closing since not a pax issue; feel free to reopen if I'm wrong

**Comment by pdeperio** [comment]
I finished the transfer manually with 'rsync --append' (was going to notify you when you returned) and started the processing manually.

**Comment by tunnell** [comment]
The run DB still correct?

**Comment by pdeperio** [comment]
I was waiting for you and Jelle to return to show me how to fix the DB

Though at the moment, I just moved the old folder and restarted the transfer (manually) to double check, so technically it is correct right now.

**Comment by pdeperio** [comment]
Sorry, looks like my previous manual transfer did not complete. Should be finished now and retrying the processing.

**Comment by pdeperio** [comment]
Processing succeeded. Sorry again.
