### ISSUE TITLE
Saner trigger data format

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#377]
The trigger data format we currently use, lots of documents with `data=bson.Binary(numpy_array.tostring())`, is not very nice for code that has to read it (see #347). Alternatives would be:
- Store the data as we do now, but use a text format. This way we can at least query the data in Mongo.
- Store each type of trigger data (e.g. the rates per PMT, or the histograms of the signal types) in a separate document, which is regularly updated. Although this creates largish documents (say a few MB), it is the simplest for just retrieving all the data for a big plot.
- ..?

**Comment by coderdj** [comment]
I think adding to_list is by far the easiest thing to do. So maybe just do that. This allows more complex queries, like if we just want to pull data from one channel. Right now we have to unpack the entire document. 

I think if you do option 2 (updating one document) you'll possibly hit the situation for long runs where a document size could exceed the 16MB limit. Or maybe this isn't possible, I didn't do the math. But I think option 1 is the more robust solution.

**Comment by JelleAalbers** [comment]
This was solved in #420
