### ISSUE TITLE
Trigger *must* save all sum waveform data

### ISSUE THREAD

**Issue by coderdj** [XENON1T/pax#414]
Channel 254 (the analog sum) must be saved for the entire run. That's the entire point of this channel, that one can see what's going on during a busy or between triggers.

**Comment by JelleAalbers** [comment]
Looks like the acquisition monitor data is currently about 200 MB/day (based on peeking at a run in progress): we should be able to handle this.

I'm thinking of just serializing the docs to a file to be placed among the raw data, just before we clear a (sub)collection. You can then iterate through it or restore it to Mongo if you want to find something. There can eventually be a hax tool for this just like for trigger monitor and slow control data.

Ideally we should have a format that doesn't require a finishing step (so not zip files) so if the eventbuilder crashes mid-run we still have the data data. Maybe just stacked bsons; maybe that's event the mongodump format? We wouldn't even need to compress.

I just realized this makes the online dead time calculation superfluous: if we store the busy-on and busy-off signals, we can do the calculation later on... if I realized this sooner I would have done this months ago. ;-)

**Comment by JelleAalbers** [comment]
Hopefully this https://github.com/XENON1T/pax/commit/374ade0d99ad1a0462f142a95213f73f4f00e2ae will address it, so we can roll it out together with the event builder upgrade from today/tomorrow

**Comment by JelleAalbers** [comment]
Yes, it will go into a file you can load with something like:
```
docs = []
with open(filename, 'rb') as infile:
    while True:
        try:
            docs.append(pickle.load(infile))
        except EOFError:
            break
```
if it's too slow we can always add compression, but 200 MB/day should be no problem.

(p.s. I'm committing this to master as I won't have much time to roll this out on the DAQ; easier to work with one branch rather than test every feature separately in separate branches. I think. If it turns out the new features interfere with each other I'll admit I was wrong).

**Comment by JelleAalbers** [comment]
Seems to be working. There is no guarantee the pulses come into the file in order though: you'll just have to load all the docs from the file, then either sort them and do your own logic or insert them into Mongo.

On a one-minute background_stable run this was less than a MB, so the file size will probably be manageable.
