### ISSUE TITLE
Hitfinder integration bound setting may lead to biased hit areas

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#433]
We currently stop integrating the hit when it reaches the level of 2x the noise. This introduces a bias to smaller hit areas. I introduced this on purpose in https://github.com/XENON1T/pax/pull/369 to avoid the high variance introduced by integrating to 0 or 1x the noise.

However, it seems the bias in area may be larger than I thought. Here's what I got today looking at single electrons in run 3410 (from last Thursday):

![hit_area_bias](https://cloud.githubusercontent.com/assets/4354311/19278755/cec29eec-8fde-11e6-9324-c0c4f21394de.png)

So the average area per hit is 0.85 pe... while there should be several other effects to push it higher than 1 pe:
- Double photoelectron emission
- Photoelectron detection efficiency (self-trigger and hitfinder) is worse for small pulses
- Pile-up of several photons into a single hit (although this is somewhat unlikely given how sparse single electrons are)

We shouldn't have such a large bias in the hit areas: it will introduce nonlinearities in our S1 and especially S2 scale. For example, a big and shallow S2 will have most of its photons sitting on top of each other, so the integration length bias is negligible. Not so for a small and deep S2. 

Instead of fiddling around with the 'low threshold' that determines the integration length, we could have a look at changing the integration algorithm altogether, e.g. to use a fixed integration length around excursions above the threshold. Payam made a study of this in this note: https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:cal:led:integration_length

**Comment by tunnell** [comment]
This is similar to what @ershockley has been studying.  @richardsaldanha do you have any thoughts here?

**Comment by JelleAalbers** [comment]
For the record, most of this bias was due to an incorrect (at the time) assumption on the PMT gains, which has been fixed. @arjenwildeboer is looking into what the best settings would be for the hitfinder integration range; his study will hopefully tell us what bias is remaining and how to fix it.

**Comment by JelleAalbers** [comment]
Adressed by #479
