### ISSUE TITLE
Mongo client maker prints passwords to output

### ISSUE THREAD

**Issue by coderdj** [XENON1T/pax#449]
The Mongo client maker logs an entire MongoDB URI to console including the password. The default when using hax is to have debug output on, so when calling pax from hax (i.e. in the raw_data class) the database password is printed.

This makes it hard to share notebooks. Even if we do everything right by putting the DB password in an environment variable, pax just prints it to the screen automatically.

**Comment by JelleAalbers** [comment]
Hi Dan, yes, this is true. For the moment we do not share notebooks with debug output publicly, nor do I expect we will do this anytime soon, but I agree there is a risk someone inadvertently posts this and discovers our password.

For now I've just disabled the debug statement, if we need to debug we can turn it on again.
