### ISSUE TITLE
Need to specify MV input format

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#464]
_From @pietrodigangi  on November 28, 2016 9:34 EST_

> List of MV runs showing transfer (or processing) errors since 23/11/2016:
161124_0030
161124_0630
161124_1202
161124_1446
161124_1510
161124_1517
161124_1547
161124_1619
161124_1707
161124_2330
161125_0530
161125_0955
161125_1058
161125_1202
161125_1356
161125_1620
161125_1652
161125_1710
161125_1728
161125_1915
161126_1407
161126_1413
161127_0213
161127_1415
161128_0215

>I tried to manually process the MV datasets
161124_0030 and 161128_0215.

>I used the command on midway:
paxer --input /project/lgrandi/xenon1t/raw/${run_name} --input_type zbson --config XENON1T_MV --config_str [Queues]max_blocks_on_heap=1000 --output myprocess_${run_name}

>and it seems that all went fine.

_Split from original issue: https://github.com/XENON1T/pax/issues/463_

**Comment by pdeperio** [comment]
Should be fixed by https://github.com/XENON1T/cax/pull/61, cax release https://github.com/XENON1T/cax/releases/tag/v4.10.3

Now in production on Midway. @pietrodigangi can you please re-check those runs if it worked?

**Comment by pietrodigangi** [comment]
I see some MV datasets starting from 4 nov 2106 correctly processed (with paxv6.1.0). for how long we should wait to check if all dataset are processed?

**Comment by JelleAalbers** [comment]
@pdeperio @pietrodigangi is this solved?

**Comment by JelleAalbers** [comment]
I'll assume this is solved, feel free to reopen this if not.
