### ISSUE TITLE
Nondeterministic segfaults on Travis

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#469]
Some of our travis builds fail with segfaults like these:
  * https://gist.github.com/JelleAalbers/23ae7036ff397f1891f133e6b054d67a
  * https://gist.github.com/JelleAalbers/722e82fe4dc625a9d88c0cb0122b4e8d

Restarting the build usually fixes the problem. From these two segfaults I would guess it is some interaction between ROOT and matplotlib, although I've heard that I have to be careful concluding things from a sample size of 2 :-)

**Comment by tunnell** [comment]
Good to keep track of, but let's not fix unless it remains a problem.  Maybe it'll solve itself...

**Comment by JelleAalbers** [comment]
Still happening
