### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#492]
When trying to run with ```--plot_to_dir``` option on a Midway batch compute node, receive the following error:
```
 : cannot connect to X server localhost:15.0
```
resulting in no output image.

Any idea how to fix?

**Comment by tunnell** [comment]
Try:

export DISPLAY=

That doesn't work?  You're trying to write an X server that doesn't exist.

**Comment by pdeperio** [comment]
```unset DISPLAY``` works, thanks!

**Comment by JelleAalbers** [comment]
We check for DISPLAY here: https://github.com/XENON1T/pax/blob/master/bin/paxer#L18. If anyone knows of another way to check for the absence of a graphics environment please let us know. We did use some other way earlier: do plt.show() and see it doesn't crash. However, it's not very nice to start people's pax experience with a crash...
