### ISSUE TITLE
Store events per file in RunsDB

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#493]
Pulling an individual (.zip) file with Rucio (e.g. for waveform watching) requires the number of events per file a priori. Could this be added to each run entry in the RunsDB?

**Comment by JelleAalbers** [comment]
Yes, this can be done. The easiest way is to explictly set `events_per_file = xxx` in the `Zip` section (subdictionary) of the processor config override section (`processor`) in the DAQ run mode settings. 

Getting it from the effective configuration at runtime is also possible, but the input plugin (MongoDB) has access to the runs db, but only the output plugin (child of FolderIO) is supposed to know this number. We could do some hacking to get it out, but some maintainer in a few years is going to curse us for it.

For existing runs I suppose you'll have to look at the pax_info.json metadata file that should come with the raw data (maybe this file can be given the same fate as https://github.com/XENON1T/cax/pulls?q=is%3Apr+is%3Aclosed). There will be some

**Comment by JelleAalbers** [comment]
This was added on 21 September 2017 (see email to computing/daq), the value can be found under
```
rundoc['reader']['ini']['trigger_config_override']['Zip']['events_per_file']
```
If no value is present (for older runs), 1000 events per file should be assumed. The final file in the run will have fewer events (`total number of events % events_per_file`).
