### ISSUE TITLE
Waveforms: Amplitude normalization

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#506]
Amplitude of single PEs seems to be on average 0.5 pe/bin. Shouldn't it be 1? Is there some normalization issue? - @lgrandi

**Comment by JelleAalbers** [comment]
It should be larger than one. I think it is in the new pax. Could you provide a bit more details on this observation?

**Comment by JelleAalbers** [comment]
Ah, you mean amplitude, not area. No, the amplitude is definititely < 1, most of the are is not in the first sample. There is a long tail up to 200ns that is still causing me headaches: https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:double_pe_emission#updatesource_of_the_discrepancy_in_mean_gain
