### ISSUE TITLE
Travis builds fail, trying to install python 3.6?

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#508]
Since yesterday all our travis builds are failing with this error:

    conda install -q conda=4.1.1

    Fetching package metadata .........

    Solving package specifications: .

    UnsatisfiableError: The following specifications were found to be in conflict:

      - conda 4.1.1* -> conda-env >=2.5,<2.6 -> python 2.7* -> openssl 1.0.1*

      - python 3.6*

    Use "conda info <package>" to see the dependencies for each package.

    The command "conda install -q conda=4.1.1" failed and exited with 1 during .

**Comment by pdeperio** [comment]
we are also now using ```conda 4.2.16``` on Midway because of https://github.com/XENON1T/cax/issues/74

**Comment by l-althueser** [comment]
How do you install pax at the moment? On my local machine i can not use `conda=4.1.1` and with `conda=4.3.11` some packages have conflicts with `python 3.4*` but it is not possible to install `python 3.6*`. If there is a clear way of installing the recent pax version the `README.md` should be updated :)
