### ISSUE TITLE
z and drift mismatch?

### ISSUE THREAD

**Issue by lgrandi** [XENON1T/pax#509]
Looking at the waveforms I saw that events that occur on the cathode @ a drift time = 675us are located at -89cm instead of -96.7cm. From this note 
https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:aalbers:drift_and_diffusion#results
the maximu drift time should be at 673us for our configuration.
This mismatch explains also the nature of the weird population that we see in run 5702 likely to be due to S1 events below the cathode with an associated secondary peak (too small to be real) associated to electron from photoionization on the cathode occurring at -89cm.

**Comment by pdeperio** [comment]
should be fixed by https://github.com/XENON1T/cax/pull/79

**Comment by JelleAalbers** [comment]
Resolved (and responsibility of cax :-) )
