### ISSUE TITLE
Potential small S2 mis-classification as S1

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#541]
From [the waveform watching campaign](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:firstresults:waveform_watching), ~1% of events found to potentially have S2s misclassified as S1s. Examples below as well as event lists of categories ```3f``` on [the waveform watching spreadsheet](https://docs.google.com/spreadsheets/d/1vggMO1r7Ev8SOuYG3VYIHNLdIzGym7vo5kBWQjBM_yY/edit?ts=58a4cd8f#gid=878005143).

This may be improved by the upcoming PR https://github.com/XENON1T/lax/pull/33, which should eventually be merged into pax classification.

![161228_0607_91731_zoom](https://cloud.githubusercontent.com/assets/8642192/23680069/8ee89012-034f-11e7-9abd-f44eb05cee76.png)

![161227_1023_305314](https://cloud.githubusercontent.com/assets/8642192/23680302/5c500328-0350-11e7-9050-5adaed73b730.png)

**Comment by feigaodm** [comment]
Fixed by PR(#584, #596)
