### ISSUE TITLE
Logbook Times are not in UTC

### ISSUE THREAD

**Issue by jpienaar13** [XENON1T/pax#554]
The log book time stamps are currently reading UTC+1 instead of UTC

**Comment by mlotfiben** [comment]
Dear Jacques since when this is happening and for which detetor is this, 
TPC or MV or both. Thanks

**Comment by coderdj** [comment]
Uh @jpienaar13 did I misunderstand the issue? Trigger time stamp would refer to time in the data. That would be very bad if this time was off.

I thought the issue was with the logbook time stamps? So having nothing to do with the data?

**Comment by jpienaar13** [comment]
Sorry, I meant logbook, I was reading it as "trigger error" and typed the
wrong thing. Sorry.

**Comment by tunnell** [comment]
Not pax
