### ISSUE TITLE
Interpolation error in ClassifyPeaks

### ISSUE THREAD

**Issue by darrylmasson** [XENON1T/pax#583]
Half of my fax jobs are failing from this error. My best guess is that s1_rise_time_aft map doesn't handle boundary values properly. I'm using the latest pax version.

```
Traceback (most recent call last):
  File "/depot/darkmatter/etc/conda/env/pax/bin/paxer", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/depot/darkmatter/apps/pax/bin/paxer", line 304, in <module>
    main()
  File "/depot/darkmatter/apps/pax/bin/paxer", line 124, in main
    parallel.maybe_multiprocess(args, **config_kwargs)
  File "/depot/darkmatter/apps/pax/pax/parallel.py", line 166, in maybe_multiprocess
    pax_instance.run()
  File "/depot/darkmatter/apps/pax/pax/core.py", line 315, in run
    self.process_event(event)
  File "/depot/darkmatter/apps/pax/pax/core.py", line 276, in process_event
    event = plugin.process_event(event)
  File "/depot/darkmatter/apps/pax/pax/plugin.py", line 91, in process_event
    event = self._process_event(event)
  File "/depot/darkmatter/apps/pax/pax/plugin.py", line 108, in _process_event
    return self.transform_event(event)
  File "/depot/darkmatter/apps/pax/pax/plugins/peak_processing/ClassifyPeaks.py", line 29, in transform_event
    elif -peak.area_decile_from_midpoint[1] < self.s1_rise_time_aft(peak.area_fraction_top):
  File "/depot/darkmatter/etc/conda/env/pax/lib/python3.4/site-packages/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/depot/darkmatter/etc/conda/env/pax/lib/python3.4/site-packages/scipy/interpolate/interpolate.py", line 588, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/depot/darkmatter/etc/conda/env/pax/lib/python3.4/site-packages/scipy/interpolate/interpolate.py", line 620, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "
ValueError: A value in x_new is above the interpolation range.
```
The events I was simulating are distributed randomly in the TPC in the energy range [2,50] keV, both NR and ER.

**Comment by feigaodm** [comment]
Thanks @darrylmasson , it look weird and I will fix it. This means that you had simulated an S1 which as an area_fraction_on_top below 0 or above 1.

**Comment by darrylmasson** [comment]
This raises the question as to how we could reconstruct a peak with area_fraction_top outside of [0,1].

**Comment by feigaodm** [comment]
@darrylmasson Can you show us more detail about the event that shows this bug? It would be helpful to see how those events look like before we decide to mark them as unknown peaks. Thanks!

**Comment by darrylmasson** [comment]
I can't really produce a waveform because fax decided where it was, so the specific instruction doesn't help. I'll rerun with different settings and try to reproduce the error.

I don't know about ZLS, I'm just using the default fax options.

**Comment by feigaodm** [comment]
Thanks @darrylmasson , it would be good to see why aft can appear outside [0,1] range. Given that this interpolation worked on real data, maybe we simulated sth incorrectly. But it could be a new feature we didn't notice below.

**Comment by malfonsi** [comment]
I encountered a similar issue when trying to process 10110 (170601_1242) dataset on ULITE with the master branch of pax (pax_head). Please note that the dataset has been succesfully processed by the standard version 6.6.5 of pax used in OSG, so this issue should be a regression

**Comment by darrylmasson** [comment]
I managed to reproduce the problem, and I think it's a floating-point error. The area_fraction_top of an offending peak is `1.0000000000000002`. This could probably be fixed without loss of generality by clipping the area_fraction_top to [0,1].

**Comment by malfonsi** [comment]
Actually I think that the problem comes from the calculation of the sum of the top pmt areas in `BasicProperties.py`:

```
# Compute top fraction
peak.area_fraction_top = np.sum(peak.area_per_channel[first_top_ch:last_top_ch + 1]) / peak.area
```
Does numpy use any algorithm to mitigate the accumulation of rounding errors in the sum, such as https://en.wikipedia.org/wiki/Kahan_summation_algorithm or any other? If I google a bit, I have the impression (but not a clear answer) that numpy does not, while for the correct sum of floating point numbers you should use math.fsum().
If it is found that this is the origin of the bug (it propagates also to S1AreaFractionTopProbability.py), it should be checked also how the total area is calculated.

**Comment by feigaodm** [comment]
@darrylmasson @malfonsi I rounded the peak aft to 0 or 1 if they are not in the physical allowed region (PR #584 ). So this problem should be fixed now.
