### ISSUE TITLE
S1 patterns binning issue

### ISSUE THREAD

**Issue by l-althueser** [XENON1T/pax#602]
I found that the S1 per-PMT map has a binning issue around `z=0`. The current map is generated with only 10 bins in z which causes the AFT map to have a continuous LXe/GXe transition instead of having a hard cut at the gate. Therefore I improved the binning of the map (increased the number of bins to 60) before interpolating and extrapolating.

I tried to test this new map with the following command and the montecarlo scripts (which seems to not be successful):
```
# fax+pax run-dependent configuration
FAX_PAX_CONFIG="[WaveformSimulator]drift_field=82 * V / cm;truth_file_name=\"${FAX_FILENAME}\";diffusion_constant_liquid=${DIFFUSION_CONSTANT} * cm**2 / s;s1_patterns_file=\"${start_dir}/XENON1T_s1_xyz_patterns_Aug2017.json.gz\";s2_mean_area_fraction_top=0.6323;[DEFAULT]drift_velocity_liquid=${DRIFT_VELOCITY} * um / ns;electron_lifetime_liquid=${ELECTRON_LIFETIME} * us"
```

The S1 AFT still looks like [on this wiki page](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:sim:notes:althueser:xe1t_msc_mc_perpmt#Comparison-of-mc-v0.2.1/v0.3.0-with-new-binning). So I don't know if there is still an issue in FAX or if the new map wasn't loaded an thus the map look equal.

You can also see in the link how I [generate the PAX map](https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:sim:notes:althueser:xe1t_msc_mc_perpmt#Convert-to-PAX-format). I also miss an option in FAX which logs the used map or an indicator which tells me that a specific map was used ..

I will continue to try testing the map before making a PR.

**Comment by pdeperio** [comment]
can you try running locally or on Midway to confirm the map is getting loaded?

**Comment by l-althueser** [comment]
I found a way to load the map in the meantime. It is now in the dax catalogue and used by FAX/PAX. Have to wait for some jobs to finish until I can give an estimation if I solved this issue. 

I have also added a drift field and S2 mean AFT value to the config string just to see what happens.
