### ISSUE TITLE
Remove Deprecated Data Files

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/pax#604]
Can we remove old input data files that should never be used again?  (They should be stored in the version control history anyway, right?)  For example, to avoid issues such as https://github.com/XENON1T/hax/pull/140, or past confusions when running reconstruction with wrong maps.

**Comment by tunnell** [comment]
Of course, delete away!

**Comment by pdeperio** [comment]
@weiyuehuan cleaned up the NN files in #612 (thanks!)

Can the others responsible please clean up their maps?

```s1_xyz```: @l-althueser 
```s2_xy```: @pelssers 
```s1_aft```: @darrylmasson 
```s1_xyz```: @berget2 
```s2_xy```: @adambrown1

**Comment by JelleAalbers** [comment]
If you have old data processed with these maps, keeping them around allows you to re-correct. They'll be in the repo somewhere, but it will be harder for most people to do some study comparing pax versions. I don't know if that's worth some confusion potential like https://github.com/XENON1T/hax/pull/140 -- though weren't these map names set by the corrections db now?

**Comment by pdeperio** [comment]
@JelleAalbers, I was also worried about an (undocumented) issue with a previous reprocessing that took an obsolete NN map filename from the outdated RunsDB, and was only discovered after someone analyzed the position distribution.  (The other maps are indeed taken care of in hax now, but as https://github.com/XENON1T/hax/pull/140 shows, we can still make this kind of mistake there.)

I agree it's a bit more difficult to do direct comparisons without all the maps in one package, but I hope it's enough to have them all in the existing conda environments.
