### ISSUE TITLE
Latest numpy required (really?) but not yet available from conda

### ISSUE THREAD

**Issue by JelleAalbers** [XENON1T/pax#674]
In https://github.com/XENON1T/pax/pull/673 we started using a numpy >= 1.12 feature, but numpy 1.11 is the latest available version with python 3.4 through the regular conda channels. I see you solved this by adding 'pip install numpy' to the travis guidelines. However, this doesn't do the detailed dependency checks that conda does (for example, numba relies on numpy and might now break something else in pax).

Hopefully anaconda's numpy will update soon. In the meantime, could https://github.com/XENON1T/pax/pull/673 be implemented without using the signature argument? I'd rather not replace conda numpy with pip numpy on the eventbuilder, so I can't use the  latest pax at the moment.

**Comment by feigaodm** [comment]
Thanks for the report,  can @zhut19 help to fix it?

**Comment by zhut19** [comment]
Thanks @JelleAalbers, I can remove the signature kwarg by commenting out the np vectorize section of the pull request, but I wasn't able to find a way using np vectorization here without this kwarg.

And this pull request would still decrease the interpolation time without this np vectorization. So do @JelleAalbers @feigaodm we agree on go back a step for now?

**Comment by feigaodm** [comment]
@zhut19 Can you keep the cKDTree in the code so we still expect some speed improvement?

**Comment by zhut19** [comment]
Yes, the cKDTree can still be in there.

**Comment by feigaodm** [comment]
ok, then I agree, please make a PR for it.

**Comment by feigaodm** [comment]
fixed by #676
